version: "3.9"

services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - redisdb
  insight:
    image: redislabs/redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db
    networks:
      - redisdb

networks:
  redisdb:

volumes:
  redisinsight:
